services:
    app.installer.ezc_demo_installer:
        autowire: true
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\EzCommerceCleanInstaller
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
            - [setServices, ["@ezpublish.api.repository", "@kernel"]]
        tags:
            - { name: ezplatform.installer, type: ezc-tmp-clean-installer }
